# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tie-File-AsHash
version:      0.09
version_from: lib/Tie/File/AsHash.pm
installdirs:  site
requires:
    Tie::File:                     
    Tie::Array::AsHash:                     

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
